version: '2'

services:
  web:
    build: ./php
    container_name: eermolaev
    depends_on:
      - database.dev
      - mailcatcher
    ports:
      - "9880:80"
      - "443:443"
    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254
    volumes:
      - ./html/:/var/www/html
  web_secure:
    build: ./php
    container_name: secure_mage
    depends_on:
      - database.dev
      - mailcatcher
    ports:
      - "4433:443"
    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254
    volumes:
      - ./html/:/var/www/html

  database.dev:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: mage
      MYSQL_PASSWORD: mage
      MYSQL_DATABASE: magento
    volumes:
      - ./data/mysql:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
